# Generated by Django 5.1.3 on 2024-12-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_shippingaddress_customer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
